name: firebasestarter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.5
  provider: ^4.0.5
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.1
  firebase_helpers: ^0.1.4
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.3+3
  firebase_messaging: ^6.0.13
  firebase_storage: ^3.1.5
  firebase_remote_config: ^0.3.0+3
  flutter_localizations:
    sdk: flutter
  google_fonts: ^0.5.0+1
  image_picker: ^0.6.5
  image_cropper: ^1.2.1
  flutter_svg: ^0.17.4
  package_info: ^0.4.0+16
  device_info: ^0.4.2+1
  flutter_auth_buttons: ^0.8.0
  flutter_swiper: ^1.1.6
dev_dependencies:
  intl_translation: ^0.17.0
  flutter_automation: ^1.3.2
  change_app_package_name: ^0.1.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
